// Generated by Wrangler on Wed Jul 03 2024 12:15:20 GMT+0100 (Irish Standard Time)
// by running `wrangler types`

interface Env {
	GITHUB_REPO: "orangejuice/blog";
	WEBSITE_URL: "https://orangejuice.cc";
	GITHUB_PRIVATE_KEY: string;
	blog: D1Database;
}
