// Generated by Wrangler on Sun Jun 16 2024 20:32:04 GMT+0100 (Irish Standard Time)
// by running `wrangler types`

interface Env {
	GITHUB_APP_ID: string;
	GITHUB_PRIVATE_KEY: string;
	GITHUB_REPO: string;
	WEBSITE_URL: string;
	blog: D1Database;
}
